Add database
zlov82/java-filmorate pull request #7
Opened 2024-11-14 23:23 UTC by zlov82

2024-11-17 10:19 UTC, YazykovMikhail requested changes

2024-11-17 10:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/repository/JdbcFilmStorage.java
> +    public Film getFilmById(long filmId) {
Данные по Mpa получай сразу
```
	public Film get(long id) {
		final String sqlQuery = "select * from FILMS f, MPA m where f.MPA_ID = m.MPA_ID AND FILM_ID = ?";
		final List<Film> films = jdbcTemplate.query(sqlQuery, DbFilmStorage::makeFilm, id);
		if (films.size() != 1) {
			throw new DataNotFoundException("film id=" + id);
		}
		return films.get(0);
	}
```

2024-11-17 10:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/repository/JdbcFilmStorage.java
> +    public Film getFilmById(long filmId) {
```
	static Film makeFilm(ResultSet rs, int rowNum) throws SQLException {
		return new Film(
				rs.getLong("film_id"),
				rs.getString("FILMS.name"),
				rs.getString("description"),
				toLocalDate(rs.getDate("release_date")),
				rs.getLong("duration"),
				rs.getLong("rate"),
				new Mpa(rs.getLong("MPA.mpa_id"), rs.getString("MPA.name")));
	}
```

2024-11-17 10:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/JdbcFilmService.java
> +        film.setMpa(mpaStorage.getMpaById(film.getMpa().getId()));
СТоит избегать дополнительных запросов к бд, если можно получить данные одним запросом, стоит это делать.
Соеденениие с БД тяжеловестная операция, получать связанные данные в sql это базовая вещь

2024-11-17 10:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/JdbcFilmService.java
> +        film.setGenres((LinkedHashSet<Genre>) genreStorage.getFilmGenres(id));
Вот тут сложнее, тут связь многие ко многим и у тебя не плохое решение, молодец! 
Только лучше избегать приведения типов, если это можно.
        film.setGenres(new LinkedHashSet<>(genreStorage.getFilmGenres(id)));

2024-11-17 10:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/JdbcFilmService.java
> +            film.setMpa(mpaStorage.getMpaById(film.getMpa().getId()));
Тут поправь по анлогии c getFilm

2024-11-17 10:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/JdbcFilmService.java
> +        for (Film film : filmsList) {
А вот вызывать запросы в цикле это не очень, на каждый вызов новое пожключение.
Поэтому можно сделать вот так:
С Мпа ты уже понял как поступиь, а с жанрами:
		genreStorage.load(films);

2024-11-17 10:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/JdbcFilmService.java
> +        for (Film film : filmsList) {
А метод буде твыглядеть как то так:
```
	@Override
	public void load(List<Film> films) {
		String inSql = String.join(",", Collections.nCopies(films.size(), "?"));
		final Map<Long, Film> filmById = films.stream().collect(Collectors.toMap(Film::getId, identity()));
		final String sqlQuery = "select * from GENRES g, FILM_GENRES fg where fg.GENRE_ID = g.GENRE_ID AND fg.FILM_ID in (" + inSql + ")";
		jdbcTemplate.query(sqlQuery, (rs) -> {
			final Film film = filmById.get(rs.getLong("FILM_ID"));
			film.addGenre(makeGenre(rs, 0));
		}, films.stream().map(Film::getId).toArray());
	}

	static Genre makeGenre(ResultSet rs, int rowNum) throws SQLException {
		return new Genre(
				rs.getLong("genre_id"),
				rs.getString("name"));
	}
```

2024-11-17 10:19 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +    description varchar(200)    NOT NULL,
Вот как рза поле likesCounter можно хранить, только назвать его как нибудь
rate, что бы при каждом запросе не пересчитывать популярность
В репозитории покажу как реализовать

2024-11-17 10:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/repository/JdbcFilmStorage.java
> +
Работу с лайками стоит вынести в отедльный репозиторий.
Один репозитторий - один обьект

2024-11-17 10:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/repository/JdbcFilmStorage.java
> +
Во время вызова addLike  и removeLike можно вызывать метод по обновлению рейтинга фильма:
```
	private void updateRate(long filmId) {
		String sqlQuery = "update FILMS f set rate = (select count(l.user_id) from LIKES l where l.film_id = f.film_id)  where film_id = ?";
		jdbcTemplate.update(sqlQuery, filmId);
	}
```
И тогда полсчет популярности будет проще. Ведь добавлени/удаление алйка просиходит намногор реже, чем получения рейтинга фильма. Поэтому лучше подсчитывтаь это в момент изменения, а не каждый раз при запросе

2024-11-17 10:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/repository/JdbcUserStorage.java
> +
Работу с друзьями стоит вынести в отедльный репозиторий.
Один репозитторий - один обьект

2024-11-17 10:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenresController.java
> +
Нет логирования

2024-11-17 10:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +
Нет логирования

2024-11-17 11:05 UTC, zlov82 commented on src/main/java/ru/yandex/practicum/filmorate/repository/JdbcFilmStorage.java
> +    public Film getFilmById(long filmId) {
Да, принцип понял, спасибо. Оставил свою реализацию через rowmapper

2024-11-18 18:30 UTC, YazykovMikhail approved these changes

2024-11-18 19:43 UTC, merged